/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diskosemka2.simJadro;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import pozicovna.Minibus;
import pozicovna.SimJadroPozicovna;

/**
 *
 * @author davidecek
 */
public class GUI extends javax.swing.JFrame implements Obs {

    /**
     * Creates new form GUI
     */
    private SimJadroPozicovna pozicovna;
    private boolean pozastav;
    private int simRep;
    private DefaultTableModel dtm;
    private XYDataset dataset;
    private JFreeChart chart = null;
    private XYSeries series1;
    private int counter;
    private double hornaHranica;
    private double spodnaHranica;
    private int i;

    public GUI() {
        String col[] = {"Cislo Minibusu", "Pozicia ", "% z trate", "Pozicia 2"};
        dtm = new DefaultTableModel(col, 0);
        pozastav = false;
        simRep = 0;
        counter = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        nadpis = new javax.swing.JLabel();
        Turbo = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pocZamTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pocMinibusTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pocReplText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        priemCasTerm1Lab = new javax.swing.JLabel();
        priemCasTerm2Lab = new javax.swing.JLabel();
        priemCasObsluhaLab = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        celkCasVSysteme = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        obsluhaLabel = new javax.swing.JLabel();
        term2Label = new javax.swing.JLabel();
        term1Label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        vytPracovnikov = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        intSpol = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        panelGraf1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pocetZamSim = new javax.swing.JTextField();
        pocMinSim = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        vyslTerm1 = new javax.swing.JLabel();
        vyslTerm2 = new javax.swing.JLabel();
        vyslTerm3 = new javax.swing.JLabel();
        vyslCasTerm1 = new javax.swing.JLabel();
        vyslCasTerm2 = new javax.swing.JLabel();
        vyslVytazenost = new javax.swing.JLabel();
        vyslCasObsluha = new javax.swing.JLabel();
        vyslCasSystem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        simCas = new javax.swing.JLabel();
        spomalenie = new javax.swing.JSlider();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        grafZam = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nadpis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nadpis.setText("Turbo mód");

        Turbo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TurboMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TurboMousePressed(evt);
            }
        });

        jLabel6.setText("Pocet Zamestnancov:");

        pocZamTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocZamTextField.setText("18");
        pocZamTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pocZamTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Pocet Minibusov:");

        pocMinibusTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocMinibusTextField.setText("7");

        jButton1.setText("Spusti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Pocet Replikacii:");

        pocReplText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocReplText.setText("100");

        jButton2.setText("prerus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("priemerny cas v rade term 1:");

        jLabel9.setText("priemerny cas v rade term 2:");

        jLabel10.setText("priemerny cas v rade pred obsluhou:");

        priemCasTerm1Lab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priemCasTerm1Lab.setText("0");

        priemCasTerm2Lab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priemCasTerm2Lab.setText("0");

        priemCasObsluhaLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priemCasObsluhaLab.setText("0");

        jLabel11.setText("celkovy cas cestujuceho v systeme:");

        celkCasVSysteme.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        celkCasVSysteme.setText("0");

        jLabel2.setText("pocet ludi terminal 1:");

        jLabel3.setText("pocet ludi terminal 2:");

        jLabel5.setText("pocet ludi pred obsluhou:");

        obsluhaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        obsluhaLabel.setText("0");

        term2Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        term2Label.setText("0");

        term1Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        term1Label.setText("0");

        jLabel12.setText("vytazenost pracovnikov:");

        vytPracovnikov.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vytPracovnikov.setText("0");

        jLabel1.setText("interval spolahlivosti:");

        intSpol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intSpol.setText("<0;0>");

        jButton8.setText("stop");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pocReplText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pocMinibusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                            .addComponent(pocZamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(43, 43, 43)
                        .addComponent(priemCasTerm2Lab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                            .addComponent(priemCasTerm1Lab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(obsluhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(term2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(term1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celkCasVSysteme, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vytPracovnikov, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priemCasObsluhaLab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intSpol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocZamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(term1Label)
                    .addComponent(jLabel10)
                    .addComponent(priemCasObsluhaLab))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocMinibusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(term2Label)
                    .addComponent(jLabel12)
                    .addComponent(vytPracovnikov))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocReplText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5)
                    .addComponent(obsluhaLabel)
                    .addComponent(jLabel11)
                    .addComponent(celkCasVSysteme))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(priemCasTerm1Lab)
                    .addComponent(jLabel1)
                    .addComponent(intSpol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton8))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(priemCasTerm2Lab))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        Turbo.addTab("Turbo mod", jPanel1);

        jButton5.setText("Vykresli");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGraf1Layout = new javax.swing.GroupLayout(panelGraf1);
        panelGraf1.setLayout(panelGraf1Layout);
        panelGraf1Layout.setHorizontalGroup(
            panelGraf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraf1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(1010, Short.MAX_VALUE))
        );
        panelGraf1Layout.setVerticalGroup(
            panelGraf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGraf1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addContainerGap(404, Short.MAX_VALUE))
        );

        Turbo.addTab("Graf zavislosti na pocte minibibusov", panelGraf1);

        jLabel14.setText("Pocet zamestnancov:");

        jLabel15.setText("Pocet minibusov:");

        pocetZamSim.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocetZamSim.setText("18");

        pocMinSim.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pocMinSim.setText("7");

        jLabel16.setText("pocet ludi terminal 1:");

        jLabel17.setText("pocet ludi terminal 2:");

        jButton3.setText("Start");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel18.setText("pocet ludi pred obsluhou:");

        jLabel19.setText("priemerny cas v rade term 1:");

        jLabel20.setText("priemerny cas v rade term 2:");

        jLabel21.setText("vytazenost pracovnikov:");

        jLabel22.setText("priemerny cas v rade pred obsluhou:");

        jLabel23.setText("celkovy cas cestujuceho v systeme:");

        vyslTerm1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslTerm1.setText("0");

        vyslTerm2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslTerm2.setText("0");

        vyslTerm3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslTerm3.setText("0");

        vyslCasTerm1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslCasTerm1.setText("0");

        vyslCasTerm2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslCasTerm2.setText("0");

        vyslVytazenost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslVytazenost.setText("0");

        vyslCasObsluha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslCasObsluha.setText("0");

        vyslCasSystem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vyslCasSystem.setText("0");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cislo Minibusu", "Pozicia 1", "% z trate", "Pozicia 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel24.setText("Simulacny cas:");

        simCas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        simCas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simCas.setText("00:00:00");

        spomalenie.setMaximum(1000);
        spomalenie.setValue(0);
        spomalenie.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spomalenieStateChanged(evt);
            }
        });

        jButton4.setText("prerus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel27.setText("Spomalenie:");

        jButton7.setText("stop");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pocetZamSim)
                                            .addComponent(pocMinSim, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel21))
                                        .addGap(118, 118, 118)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vyslVytazenost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslTerm2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslTerm3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslCasTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslCasTerm2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslCasObsluha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslCasSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vyslTerm1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addGap(70, 70, 70)
                        .addComponent(spomalenie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simCas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(pocetZamSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(pocMinSim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(vyslTerm1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(vyslTerm2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(vyslTerm3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(vyslCasTerm1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(vyslCasTerm2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(vyslCasObsluha))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(vyslVytazenost))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(vyslCasSystem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spomalenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simCas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Turbo.addTab("Simulacia", jPanel2);

        jButton6.setText("vykresli");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grafZamLayout = new javax.swing.GroupLayout(grafZam);
        grafZam.setLayout(grafZamLayout);
        grafZamLayout.setHorizontalGroup(
            grafZamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grafZamLayout.createSequentialGroup()
                .addComponent(jButton6)
                .addGap(0, 1020, Short.MAX_VALUE))
        );
        grafZamLayout.setVerticalGroup(
            grafZamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grafZamLayout.createSequentialGroup()
                .addComponent(jButton6)
                .addGap(0, 415, Short.MAX_VALUE))
        );

        Turbo.addTab("Graf zavislosti na pocte zamestnancov", grafZam);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nadpis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Turbo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(nadpis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Turbo, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int pocetAut = Integer.parseInt(pocMinibusTextField.getText());
        int pocetPracovnikov = Integer.parseInt(pocZamTextField.getText());
        int pocetReplikacii = Integer.parseInt(pocReplText.getText());
        pozicovna = new SimJadroPozicovna(pocetReplikacii, 0, 2592000, pocetAut, pocetPracovnikov, false);
        pozicovna.registerDelegate(this);
        simRep = 0;
        i = 0;
        pozicovna.spusti();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pozicovna.pozastav();
        if (!pozastav) {
            jButton2.setText("pokracuj");
            pozastav = true;
        } else {
            pozastav = false;
            jButton2.setText("prerus");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int pocetAut = Integer.parseInt(pocMinSim.getText());
        int pocetPracovnikov = Integer.parseInt(pocetZamSim.getText());
        int pocetReplikacii = 1;
        int rychlost = spomalenie.getValue();
        pozicovna = new SimJadroPozicovna(pocetReplikacii, rychlost, 2592000, pocetAut, pocetPracovnikov, false);
        pozicovna.registerDelegate(this);
        simRep = 1;
        dtm.setRowCount(0);

        for (int i = 0; i < pocetAut; i++) {
            dtm.addRow(new Object[]{i, "", "", ""});
            dtm.setValueAt(i, i, 0);
        }
        pozicovna.spusti();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TurboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TurboMouseClicked
        nadpis.setText("Turbo mód");
    }//GEN-LAST:event_TurboMouseClicked

    private void TurboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TurboMousePressed

    }//GEN-LAST:event_TurboMousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        pozicovna.pozastav();
        if (!pozastav) {
            jButton4.setText("pokracuj");
            pozastav = true;
        } else {
            pozastav = false;
            jButton4.setText("prerus");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pocZamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pocZamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pocZamTextFieldActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        hornaHranica = Double.MIN_VALUE;
        spodnaHranica = Double.MAX_VALUE;
        panelGraf1.setLayout(new java.awt.BorderLayout());
        XYSeriesCollection dataset = new XYSeriesCollection();
        series1 = new XYSeries("Priemerny cas");
        chart = ChartFactory.createXYLineChart("Graf zavislosti na pocte minibusov", "pocet minibusov", "Priemerny cas v systeme", dataset);
        dataset.addSeries(series1);
        ChartPanel chartPanel = new ChartPanel(chart);
        panelGraf1.add(chartPanel, BorderLayout.CENTER);
        panelGraf1.validate();
        simRep = 2;
        for (int i = 3; i <= 20; i++) {
            counter++;
            SimJadroPozicovna pozicovna = new SimJadroPozicovna(10, 0, 2592000, i, 18, true);
            pozicovna.registerDelegate(this);
            pozicovna.spusti();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        hornaHranica = Double.MIN_VALUE;
        spodnaHranica = Double.MAX_VALUE;
        grafZam.setLayout(new java.awt.BorderLayout());
        XYSeriesCollection dataset = new XYSeriesCollection();
        series1 = new XYSeries("Priemerny cas");
        chart = ChartFactory.createXYLineChart("Graf zavislosti na pocte zamestnancov", "pocet zamestnancov", "Priemerny cas v systeme", dataset);
        dataset.addSeries(series1);
        ChartPanel chartPanel = new ChartPanel(chart);
        grafZam.add(chartPanel, BorderLayout.CENTER);
        grafZam.validate();
        simRep = 3;
        for (int i = 7; i <= 30; i++) {
            counter++;
            SimJadroPozicovna pozicovna = new SimJadroPozicovna(10, 0, 2592000, 7, i, true);
            pozicovna.registerDelegate(this);
            pozicovna.spusti();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void spomalenieStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spomalenieStateChanged
        if (pozicovna != null) {
            pozicovna.setSpomalenie(spomalenie.getValue());
        }
    }//GEN-LAST:event_spomalenieStateChanged

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (pozicovna != null) {
            pozicovna.setStop();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (pozicovna != null) {
            pozicovna.setStop();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Turbo;
    private javax.swing.JLabel celkCasVSysteme;
    private javax.swing.JPanel grafZam;
    private javax.swing.JLabel intSpol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nadpis;
    private javax.swing.JLabel obsluhaLabel;
    private javax.swing.JPanel panelGraf1;
    private javax.swing.JTextField pocMinSim;
    private javax.swing.JTextField pocMinibusTextField;
    private javax.swing.JTextField pocReplText;
    private javax.swing.JTextField pocZamTextField;
    private javax.swing.JTextField pocetZamSim;
    private javax.swing.JLabel priemCasObsluhaLab;
    private javax.swing.JLabel priemCasTerm1Lab;
    private javax.swing.JLabel priemCasTerm2Lab;
    private javax.swing.JLabel simCas;
    private javax.swing.JSlider spomalenie;
    private javax.swing.JLabel term1Label;
    private javax.swing.JLabel term2Label;
    private javax.swing.JLabel vyslCasObsluha;
    private javax.swing.JLabel vyslCasSystem;
    private javax.swing.JLabel vyslCasTerm1;
    private javax.swing.JLabel vyslCasTerm2;
    private javax.swing.JLabel vyslTerm1;
    private javax.swing.JLabel vyslTerm2;
    private javax.swing.JLabel vyslTerm3;
    private javax.swing.JLabel vyslVytazenost;
    private javax.swing.JLabel vytPracovnikov;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh(SimulacneJadro simJadro) {
        i++;
        SimJadroPozicovna sim = (SimJadroPozicovna) simJadro;
        simCas.setText(simulacnyCas((long) (simJadro.getAkt_SimCas())));
        if (simRep == 0) {
            double[] vysledky = pozicovna.getCelkoveVysledky();
            DecimalFormat df = new DecimalFormat("#.###");
            this.term1Label.setText(String.valueOf(Double.valueOf(df.format(vysledky[4]))));
            this.term2Label.setText(String.valueOf(Double.valueOf(df.format(vysledky[5]))));
            this.obsluhaLabel.setText(String.valueOf(Double.valueOf(df.format(vysledky[6]))));
            this.priemCasTerm1Lab.setText(String.valueOf(Double.valueOf(df.format(vysledky[1]))));
            this.priemCasTerm2Lab.setText(String.valueOf(Double.valueOf(df.format(vysledky[2]))));
            this.priemCasObsluhaLab.setText(String.valueOf(Double.valueOf(df.format(vysledky[3]))));
            this.celkCasVSysteme.setText(String.valueOf(Double.valueOf(df.format(vysledky[0]))));
            this.vytPracovnikov.setText(String.valueOf(Double.valueOf(df.format(vysledky[7]))));
            if (i > 3) {
                this.intSpol.setText("<" + String.valueOf(Double.valueOf(df.format(vysledky[8]))) + " ; " + String.valueOf(Double.valueOf(df.format(vysledky[9]))) + ">");
            }
        } else if (simRep == 1) {
            double[] vysledky = pozicovna.getPriebezneVysledky();
            DecimalFormat df = new DecimalFormat("#.###");
            this.vyslTerm1.setText(String.valueOf(Double.valueOf(df.format(vysledky[4]))));
            this.vyslTerm2.setText(String.valueOf(Double.valueOf(df.format(vysledky[5]))));
            this.vyslTerm3.setText(String.valueOf(Double.valueOf(df.format(vysledky[6]))));
            this.vyslCasTerm1.setText(String.valueOf(Double.valueOf(df.format(vysledky[1]))));
            this.vyslCasTerm2.setText(String.valueOf(Double.valueOf(df.format(vysledky[2]))));
            this.vyslCasObsluha.setText(String.valueOf(Double.valueOf(df.format(vysledky[3]))));
            this.vyslCasSystem.setText(String.valueOf(Double.valueOf(df.format(vysledky[0]))));
            this.vyslVytazenost.setText(String.valueOf(Double.valueOf(df.format(vysledky[7]))));

            Minibus[] minibusy = pozicovna.getMinibusy();

            if (minibusy != null) {

                for (int i = 0; i < minibusy.length; i++) {
                    dtm.setValueAt(minibusy[i].getPoslednaUdalost(), i, 1);
                    double pom = sim.vypocitaPoziciuMinibusu(i);
                    if (pom > 100) {
                        pom = 0.0;
                    }
                    dtm.setValueAt(String.format("%.2f", pom), i, 2);
                    dtm.setValueAt(minibusy[i].getCinnost(), i, 3);
                }
                this.jTable1.setModel(dtm);
            } else {
                JOptionPane.showMessageDialog(null, "Nezadali ste všetky potrebne udaje");
            }
        } else if (simRep == 2) {

            double priemer = sim.getDataNaVykreslenie();
            if (priemer > hornaHranica) {
                hornaHranica = priemer + 0.000001;
            }
            if (priemer < spodnaHranica) {
                spodnaHranica = priemer - 0.000001;
            }
            if (priemer > hornaHranica) {
                hornaHranica = priemer + 0.000001;
            }
            if (priemer < spodnaHranica) {
                spodnaHranica = priemer - 0.000001;
            }
            vykresli(priemer, sim.getPocetMinibusov(), hornaHranica, spodnaHranica);

        } else if (simRep == 3) {

            double priemer = sim.getDataNaVykreslenie();
            if (priemer > hornaHranica) {
                hornaHranica = priemer + 0.000001;
            }
            if (priemer < spodnaHranica) {
                spodnaHranica = priemer - 0.000001;
            }
            if (priemer > hornaHranica) {
                hornaHranica = priemer + 0.000001;
            }
            if (priemer < spodnaHranica) {
                spodnaHranica = priemer - 0.000001;
            }
            vykresli(priemer, sim.getPocetPracujicich(), hornaHranica, spodnaHranica);
        } else if (simRep == 4) {
            double[] vysledky = pozicovna.getCelkoveVysledky();
            System.out.println("----------------------------");
            System.out.println("Pocet AUT: " + sim.getPocetMinibusov() + "Pocet pracovnikov: " + sim.getPocetPracovnikov());
            System.out.println("----------------------------");
            System.out.println(vysledky[4]);
            System.out.println(vysledky[5]);
            System.out.println(vysledky[6]);
            System.out.println(vysledky[1]);
            System.out.println(vysledky[2]);
            System.out.println(vysledky[3]);
            System.out.println(vysledky[0]);
            System.out.println(vysledky[7]);

        }
    }

    public void vykresli(double priemer, double counter, double horna, double spodna) {
        this.chart.getXYPlot().getRangeAxis().setRange(spodna, horna);
        series1.add(counter, priemer);
    }

    public static String simulacnyCas(double time) {
        long timeLong = (long) time;
        long second = timeLong % 60;
        long minute = (timeLong / 60) % 60;
        long hour = (timeLong / (60 * 60) % 24);
        long day = (timeLong / (60 * 60 * 24));
        if (day > 30) {
            return String.format("%02d dni %02d:%02d:%02d", 30, 00, 00, 00);
        } else {
            return String.format("%02d dni %02d:%02d:%02d", day, hour, minute, second);
        }
    }

}
